C***********************************************************************
C<=====
C=====> *COMDECK.LUNCOM INSERTED HERE
      COMMON /LUNITS/ TPIN,TPOUT,TPRPT,TPLOT
C
C     TPIN  = STANDARD TRANPLAN INPUT
C     TPOUT = STANDARD TRANPLAN OUTPUT
C     TPRPT = STANDARD TRANPLAN REPORT OUTPUT
C     TPLOT = STANDARD TRANPLAN PLOT OUTPUT
C
      INTEGER*4 TPIN,TPOUT,TPRPT,TPLOT
C
C***********************************************************************